### ISSUE TITLE
deploy toHeroku?

### ISSUE THREAD

**Issue by c21xdx** [Lunik/Mega-Torrent#13]
does Mega-Torrent can deploy toHeroku like [Lunik-Torrent](https://github.com/Lunik/Lunik-Torrent) as web interface , 1 click?

and i tried it on cloud 9 too, it show that
![m01](https://cloud.githubusercontent.com/assets/5766149/15653723/3850d4dc-26c1-11e6-8f32-9407c5366736.jpg)

anything else i need to do? thanks

**Comment by Lunik** [comment]
Nop it's only a nodejs module.

You can try with making an `app.js`:
````
var Mega_Torrent = require('mega-torrent')

var mega_t = new Mega_Torrent({ email: "me@me.com", password: "123456789" })

mega_t.download("magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4")
```

And then run `node app.js`

**Comment by c21xdx** [comment]
thanks, it is work. can you get me a full example which is use all the API(Main Module,Megas,Clients)? such as mega_t.getStatus(),megas.getProgress(),clients.getProgress() and so on. thanks

**Comment by Lunik** [comment]
I think that the [API Documentation](https://github.com/Lunik/Mega-Torrent) is quite clear on how the API work. 
I'm not here to write your application for you :grin:.

**Comment by c21xdx** [comment]
i am sorry, thanks

**Comment by Lunik** [comment]
That's nothing :wink:. 
Thank's for your interest for my module 😉 .
